### PR TITLE
Add abstract data object for `Dto` namespace

### LINKED ISSUE #27: Add abstract Dto class for `Dto` namespace objects
I think it may be time to use inheritance for current/future non-behavior features anyways... ⁄(⁄ ⁄•⁄-⁄•⁄ ⁄)⁄

### PR DESCRIPTION
**Pull request by BlossomiShymae**
Resolves #27 ! >:3

# Features
- **Core.PrettyPrinter**: Add overload method `GetPrettyString` for manually setting the class name
- **Dto**: Add abstract `DataObject<T>` superclass for namespace
- **Dto**: All objects now extend from the above class

### CODE REVIEW

**Comment by AoshiW** [comment]
why `DataObject<T>` has generic parametr?
I recommend to see what is the difference between class and record, because records always generate their version of `ToString`

[Magic Link](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoIsgTgAo8YB3AAgCEBDAZxgYCUAgNzVajZuwAiMKADdBI6tViQoAE068Y1AN7U2htkQDMbAJZ4MbAJJtdAcxgZhbPi4C+bALxskoqiNjMwg5WShzdRhjMgAGNgAVCABlDAi8B0EDI31AoKMiAHY2ACJgbRKAoI9qGqoVGDVNGXk2EC0+PWzDUxj45PsnFzdnYS9fEtpYytrqIA===)

**Comment by BlossomiShymae** [comment]
Hi!

It was the only solution I thought of for the abstract `ToString` method to print the Dto/Data type name for the `ToString()`. 

I tried using `GetType().Name` in a non-generic version but it gave `System.RuntimeType` (maybe I misunderstood something like always and used it wrong...)

Sorry, I'll relook into it. :3

**Comment by BlossomiShymae** [comment]
@AoshiW 

I am probably just being dumb and overthinking it again. Could I have just used a `nameof()` since I just wanted the name of the Dto to be included for the `ToString()` method? Since it is generated at compile-time, this should be way better than using a `GetType().Name` I believe? 

So then I could just totes do this:

```csharp
public record MyDto : Data
{
	public int Id { get; init; }

	public MyDto() : base(nameof(MyDto)) { }
}
```

```csharp
public abstract record DataObject
{
	private readonly string _name;

	public Data(string name)
	{
		_name = name;
	}

	public sealed override string ToString()
	{
		return PrettyPrinter.GetString(this, _name);
	}
}
```

Output for default `MyDto` instance:
```json
MyDto {
  "Id": 0
}
```

**Comment by AoshiW** [comment]
sorry for the late reply
>I tried using GetType().Name in a non-generic version but it gave System.RuntimeType (maybe I misunderstood something like always and used it wrong...)

it looks like a bug in the code
> Could I have just used a nameof() 

you can't, you'll have a problem if a class inherits from a class that already inherits from `DataObject` (ToString will print correct json but with wrong name of class)
```cs
class C1 : DataObject { public int I { get; set; } // ToString => "C1 { I: 0 }"
class C2 : C1 { public double D { get; set; } // ToString => "C1 { I: 0, D: 0.0 }"
```

I think you can simplify class to this:
```cs
public abstract record DataObject
{
	public sealed override string ToString()
	{
		return PrettyPrinter.GetString(this, GetType().Name);
	}
}
```
Yes, this not as fast as the current implementation with `Helper<T>.Name` but I don't think its a problem (I think `ToString` is not something you will use often (except debugging and console app))

**Pull request merged**
